# Azure Pipeline for a Node.js App
trigger:
  branches:
    include:
      - main # Adjust this to your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '18.x' # Specify your desired Node.js version

steps:
  # Install Node.js
  - task: UseNode@2
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Use Node.js $(NODE_VERSION)'

  # Install Dependencies
  - script: |
      npm install
    displayName: 'Install dependencies'

  # Run Tests
  - script: |
      npm test
    displayName: 'Run tests'

  # Build the App (Optional)
  - script: |
      npm run build
    displayName: 'Build the app'

  # Archive Artifacts (Optional)
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    displayName: 'Archive app'

  # Publish Build Artifacts (Optional)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
    displayName: 'Publish artifacts'

  # Deploy to Azure App Service
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Infy' # Replace with your actual service connection name
      appType: 'nodejs'
      appName: 'Infy' # Replace with your actual app service name
      package: '$(Build.ArtifactStagingDirectory)/app.zip'
    displayName: 'Deploy to Azure App Service'
