version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ankit 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: infosys 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
