name: Deploy Node.js project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'Infy'   
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Infy'       
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Install Azure Functions Core Tools'
      run: npm install -g azure-functions-core-tools@4 --unsafe-perm

    - name: 'Install Dependencies'
      shell: bash
      run: |
        echo "Installing dependencies in: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        npm install
        popd

    - name: 'Run Tests'
      shell: bash
      run: |
        echo "Running tests in: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        npm run test
        popd

    - name: 'Build Application'
      shell: bash
      run: |
        echo "Building application in: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        npm run build --if-present
        popd

    - name: 'Remove WEBSITE_RUN_FROM_PACKAGE'
      run: |
        echo "Removing WEBSITE_RUN_FROM_PACKAGE setting from Function App"
        az functionapp config appsettings delete \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --resource-group infosys \
          --setting-names WEBSITE_RUN_FROM_PACKAGE
      env:
        AZURE_FUNCTIONAPP_NAME: ${{ env.AZURE_FUNCTIONAPP_NAME }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        # ignore the warning for the line below, debug already confirmed the secret is set
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
